# Generated by Django 4.0.3 on 2022-06-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeInfoid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employeeinfo', verbose_name='Employee name')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Missed document', max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Male', max_length=15, unique=True, verbose_name='Student Gender')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNo', models.CharField(default='009988', max_length=25)),
                ('name', models.CharField(default='name', max_length=20)),
                ('surname', models.CharField(default='surname', max_length=20)),
                ('phone', models.CharField(default='009988', max_length=25, null=True)),
                ('email', models.EmailField(default='Info@studygo.com', max_length=100, verbose_name='email')),
                ('passportNo', models.CharField(default='009988', max_length=25)),
                ('documents', models.CharField(default='No', max_length=15, null=True)),
                ('reject', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=25, unique=True, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=25, unique=True, verbose_name='Residence')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='stage1', max_length=25, unique=True, verbose_name='Student Status')),
                ('statusDescription', models.CharField(max_length=25, unique=True, verbose_name='Status Description')),
            ],
        ),
        migrations.CreateModel(
            name='StudyYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyYears', models.IntegerField(default='4', unique=True, verbose_name='Study Years')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityCity', models.CharField(default='Istanbul', max_length=40, unique=True, verbose_name='University City')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='Bachelor', max_length=40, unique=True, verbose_name='Degree')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='Turkish', max_length=50, unique=True, verbose_name='language')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityName', models.CharField(default='Istanbul', max_length=50, unique=True, verbose_name='University Name')),
            ],
        ),
        migrations.CreateModel(
            name='ViewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Law', max_length=150, verbose_name='Department')),
                ('tuitionFees', models.CharField(default='1500', max_length=40, verbose_name='Tuition fees')),
                ('afterDiscount', models.CharField(default='1200', max_length=40, verbose_name='Tuition after discount')),
                ('activeSeat', models.BooleanField(default=1, verbose_name='Active seat')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universitylanguage', verbose_name='Language')),
                ('universityCity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universitycity', verbose_name='University city')),
                ('universityDegree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universitydegree', verbose_name='University Degree')),
                ('universityName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universityname', verbose_name='University name')),
                ('yearsOfStudy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studyyears', verbose_name='Study of years')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('degreePaper', models.CharField(default='degree Paper', max_length=40, null=True, verbose_name='Degree Paper')),
                ('studentid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentinfo', verbose_name='Student name')),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='degree',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.universitydegree', verbose_name='University Degree'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentgender', verbose_name='Student Gender'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentnationality', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='officeInfoid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.officeinfo', verbose_name='Office name'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentresidence', verbose_name='Residence'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='statusType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statustype', verbose_name='Status Type'),
        ),
        migrations.AddField(
            model_name='statustype',
            name='studentStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentstatus', verbose_name='Student status'),
        ),
        migrations.CreateModel(
            name='SeatsRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentInfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentinfo', verbose_name='Student Info')),
                ('universityProgram', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universityprogram', verbose_name='university Program')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentFile', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('documentName', models.CharField(default='document Name', max_length=40, null=True, verbose_name='Degree Paper')),
                ('studentid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentinfo', verbose_name='Student name')),
            ],
        ),
        migrations.CreateModel(
            name='DegreePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(default='Passport', max_length=40, verbose_name='Paper Name')),
                ('degree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universitydegree', verbose_name='University Degree')),
            ],
        ),
        migrations.CreateModel(
            name='AllUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='0090', max_length=15)),
                ('address', models.CharField(default='Istanbul', max_length=250)),
                ('residence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentresidence', verbose_name='residence')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
    ]
