# Generated by Django 3.2.8 on 2022-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprogram',
            name='afterDiscount',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='tuitionFees',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='yearsOfStudy',
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='CashFees',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='Cash Fees'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='notes',
            field=models.CharField(default='No', max_length=40, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='numberOfYears',
            field=models.CharField(default='2', max_length=40, verbose_name='Number of Years'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='systemOfPayment',
            field=models.CharField(default='Per year', max_length=40, verbose_name='System of Payment'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='taksitFees',
            field=models.CharField(default='', max_length=40, verbose_name='Taksit Fees'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='thesis',
            field=models.CharField(default='No', max_length=40, null=True, verbose_name='Thesis'),
        ),
        migrations.DeleteModel(
            name='StudyYears',
        ),
    ]
