# Generated by Django 3.2.8 on 2022-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220609_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprogram',
            name='numberOfYears',
            field=models.CharField(default='2', max_length=40, null=True, verbose_name='Number of Years'),
        ),
    ]
