# Generated by Django 3.2.8 on 2022-06-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_universityprogram_numberofyears'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=25, unique=True, verbose_name='user Type')),
            ],
        ),
    ]
